CREATE TABLE courses(course_id char(20),course_name char(60),CONSTRAINT cid01 PRIMARY KEY(course_id));


INSERT INTO courses VALUES('BT101 ','Introductory Biology                                       ');
INSERT INTO courses VALUES('BT206 ','MicroBiology                                               ');
INSERT INTO courses VALUES('BT207 ','Genetic Engineering                                        ');
INSERT INTO courses VALUES('BT208 ','Transport Phenomenon in Bioprocesses                       ');
INSERT INTO courses VALUES('BT209 ','BioReaction Engineering                                    ');
INSERT INTO courses VALUES('BT302 ','Biochemical Engineering                                    ');
INSERT INTO courses VALUES('BT302M','BioProcess Technology                                      ');
INSERT INTO courses VALUES('BT305 ','Industrial Microbiology                                    ');
INSERT INTO courses VALUES('BT306 ','IPR Ethics and Bio-safety                                  ');
INSERT INTO courses VALUES('BT308 ','Animal Cell Biotechnology                                  ');
INSERT INTO courses VALUES('BT401 ','Frontiers in Biotechnology                                 ');
INSERT INTO courses VALUES('BT502 ','Quantitative Biology                                       ');
INSERT INTO courses VALUES('BT504 ','Biomolecular and Cellular Process Engineering              ');
INSERT INTO courses VALUES('BT601 ','Analytical Biotechnology                                   ');
INSERT INTO courses VALUES('BT617 ','Concepts and Methods in Proteomics                         ');
INSERT INTO courses VALUES('BT619 ','Essential of Genetics                                      ');
INSERT INTO courses VALUES('BT621 ','Advances in Plant Genetic Engg. & Functional Genomics      ');
INSERT INTO courses VALUES('BT623 ','Research Methodology                                       ');
INSERT INTO courses VALUES('BT630 ','Physical Cell Biology                                      ');
INSERT INTO courses VALUES('BT632 ','Stem Cells Cancer and Therapy                              ');
INSERT INTO courses VALUES('BT634 ','Animal Models in Biomedical Research                       ');
INSERT INTO courses VALUES('BT638 ','Cellular And Molecular Aspects of Aging                    ');
INSERT INTO courses VALUES('BT642 ','Alternatice Splicing And Diseases                          ');
INSERT INTO courses VALUES('CE201 ','Surveying                                                  ');
INSERT INTO courses VALUES('CE205 ','Structural Analysis I                                      ');
INSERT INTO courses VALUES('CE206 ','Geotechnical Engg. I                                       ');
INSERT INTO courses VALUES('CE220 ','Hydraulics & Hydraulic Structure                           ');
INSERT INTO courses VALUES('CE222 ','Environmental Engg. I                                      ');
INSERT INTO courses VALUES('CE308 ','Construction Technology and Management                     ');
INSERT INTO courses VALUES('CE309 ','Design of Steel Structures                                 ');
INSERT INTO courses VALUES('CE320 ','Engineering Hydrology                                      ');
INSERT INTO courses VALUES('CE322 ','Transportation Engineering II                              ');
INSERT INTO courses VALUES('CE324 ','Engineering Geology                                        ');
INSERT INTO courses VALUES('CE504 ','Advanced Structural Design                                 ');
INSERT INTO courses VALUES('CE510 ','Quality And Safety Management In Construction              ');
INSERT INTO courses VALUES('CE511 ','Analysis and Design of Bridges                             ');
INSERT INTO courses VALUES('CE514 ','Plates Shells And Elastic Stability                        ');
INSERT INTO courses VALUES('CE524 ','Biological Processes in Environmental Engg.                ');
INSERT INTO courses VALUES('CE525 ','Solid and Hazardous Waste Management                       ');
INSERT INTO courses VALUES('CE533 ','Advanced Foundation Engg.                                  ');
INSERT INTO courses VALUES('CE552 ','Water Resources Systems AnalysisPlanning & Management      ');
INSERT INTO courses VALUES('CE555 ','Principles of Water Quality & EIA                          ');
INSERT INTO courses VALUES('CE556 ','Subsurface Hydrology                                       ');
INSERT INTO courses VALUES('CE561 ','Water Power Engineering                                    ');
INSERT INTO courses VALUES('CE562 ','Transient Flow Analysis                                    ');
INSERT INTO courses VALUES('CE567 ','Sediment Dynamic in Fluvial Systems                        ');
INSERT INTO courses VALUES('CE583 ','Pavement Analysis and Design                               ');
INSERT INTO courses VALUES('CE584 ','Traffic Engineering                                        ');
INSERT INTO courses VALUES('CE594 ','Geohazard Science and Engineering                          ');
INSERT INTO courses VALUES('CE595 ','Advanced Techniques in Geoscience                          ');
INSERT INTO courses VALUES('CE606 ','Earthquake Engineering                                     ');
INSERT INTO courses VALUES('CE607 ','Random Vibration                                           ');
INSERT INTO courses VALUES('CE608 ','Reliability based Structural Design                        ');
INSERT INTO courses VALUES('CE612 ','Advanced Concrete Technology                               ');
INSERT INTO courses VALUES('CE614 ','Financing Infrastructure Projects                          ');
INSERT INTO courses VALUES('CE615 ','Design of Masonry Structures                               ');
INSERT INTO courses VALUES('CE618 ','Mechanics of Unsaturated Soils                             ');
INSERT INTO courses VALUES('CE622 ','Geometric Design of Transportation Facilities              ');
INSERT INTO courses VALUES('CE623 ','Pavement Evaluation Rehabilitation and Maintenance         ');
INSERT INTO courses VALUES('CE643 ','Earthquake Geotechnical Engg.                              ');
INSERT INTO courses VALUES('CE646 ','Rock Mechanics                                             ');
INSERT INTO courses VALUES('CE647 ','Environmental Geotechnology                                ');
INSERT INTO courses VALUES('CE661 ','Air Quality Modeling                                       ');
INSERT INTO courses VALUES('CE664 ','Industrial Wastewater Pollution Control                    ');
INSERT INTO courses VALUES('CH211 ','Industrial Chemistry                                       ');
INSERT INTO courses VALUES('CH222 ','Applied Organic Chemistry                                  ');
INSERT INTO courses VALUES('CH224 ','Group Theory                                               ');
INSERT INTO courses VALUES('CH232 ','Computational Chemistry                                    ');
INSERT INTO courses VALUES('CH233 ','Spectroscopic Techniques in Chemistry                      ');
INSERT INTO courses VALUES('CH322 ','Petroleum and Petrochemicals                               ');
INSERT INTO courses VALUES('CH323 ','Polymer Chemistry                                          ');
INSERT INTO courses VALUES('CH333 ','Introduction - Chemical Thermodynamics and Equilibrium     ');
INSERT INTO courses VALUES('CH400 ','Computers and Chemistry                                    ');
INSERT INTO courses VALUES('CH411 ','Inorganic Reaction Mechanism and Organometallics           ');
INSERT INTO courses VALUES('CH417 ','Organometallic Chemistry                                   ');
INSERT INTO courses VALUES('CH418 ','Biological Chemistry of Metal Ions                         ');
INSERT INTO courses VALUES('CH419 ','Consumer Chemistry                                         ');
INSERT INTO courses VALUES('CH421 ','Organic Reactions and Mechanisms                           ');
INSERT INTO courses VALUES('CH428 ','Drug Design and Development                                ');
INSERT INTO courses VALUES('CH432 ','Chemical Dynamics & Electrochemistry                       ');
INSERT INTO courses VALUES('CH433 ','Applications of Spectroscopy                               ');
INSERT INTO courses VALUES('CH501 ','Computers in Chemistry                                     ');
INSERT INTO courses VALUES('CH603 ','Concept of Molecular Machine                               ');
INSERT INTO courses VALUES('CH611 ','Bioinorganic Chemistry                                     ');
INSERT INTO courses VALUES('CH615 ','Advanced Organometallic Chemistry                          ');
INSERT INTO courses VALUES('CH617 ','Supramolecular Chemistry                                   ');
INSERT INTO courses VALUES('CH621 ','New Reagents for Organic Synthesis                         ');
INSERT INTO courses VALUES('CH623 ','Chemistry of Biological Macromolecules                     ');
INSERT INTO courses VALUES('CH625 ','Art in Organic Syntheses                                   ');
INSERT INTO courses VALUES('CH630 ','A Fundamental Approach - Physical Chemistry                ');
INSERT INTO courses VALUES('CH634 ','Computational Methods in Chemistry                         ');
INSERT INTO courses VALUES('CH637 ','Advanced Quantum Chemistry                                 ');
INSERT INTO courses VALUES('CH640 ','Principle and Applications of Luminescence Spectroscopy    ');
INSERT INTO courses VALUES('CH644 ','Applied Quantum Chemistry                                  ');
INSERT INTO courses VALUES('CL205 ','Mass Transfer - I                                          ');
INSERT INTO courses VALUES('CL206 ','Solid Fluid Operations                                     ');
INSERT INTO courses VALUES('CL207 ','Computer Aided Numerical Methods                           ');
INSERT INTO courses VALUES('CL208 ','Chemical Reaction Engineering- I                           ');
INSERT INTO courses VALUES('CL209 ','Process Equipment Design                                   ');
INSERT INTO courses VALUES('CL307 ','Transport Phenomena                                        ');
INSERT INTO courses VALUES('CL308 ','Chemical Reaction Engg. II                                 ');
INSERT INTO courses VALUES('CL309 ','Process Control and Instrumentation                        ');
INSERT INTO courses VALUES('CL314 ','Numerical Methods in Chemical Engineering                  ');
INSERT INTO courses VALUES('CL401 ','Process  Design and Project Engineering                    ');
INSERT INTO courses VALUES('CL404 ','Material Science                                           ');
INSERT INTO courses VALUES('CL503 ','Advanced Thermodynamics                                    ');
INSERT INTO courses VALUES('CL504 ','Reaction Engineering                                       ');
INSERT INTO courses VALUES('CL612 ','Colloid and Interface Science                              ');
INSERT INTO courses VALUES('CL617 ','Petrochemicals                                             ');
INSERT INTO courses VALUES('CL619 ','Refinery Process Design                                    ');
INSERT INTO courses VALUES('CL622 ','Molecular Simulation: Principles and Application           ');
INSERT INTO courses VALUES('CL623 ','Polymer Science and Technology                             ');
INSERT INTO courses VALUES('CL625 ','Fundamentals of Micro-nano Fluidics and Micro-Fabrication  ');
INSERT INTO courses VALUES('CL628 ','Catalysts and Adsorbents                                   ');
INSERT INTO courses VALUES('CL630 ','Composites Materials                                       ');
INSERT INTO courses VALUES('CL635 ','Advanced Clean Fuel Technologies                           ');
INSERT INTO courses VALUES('CL642 ','Advanced Flow Measurement Techniques                       ');
INSERT INTO courses VALUES('CL643 ','Computer Aided Applied Optimization                        ');
INSERT INTO courses VALUES('CS101 ','Introduction - Computing                                   ');
INSERT INTO courses VALUES('CS205 ','Formal Languages Automata Theory and Computation           ');
INSERT INTO courses VALUES('CS206M','Data Structures and Algorithms                             ');
INSERT INTO courses VALUES('CS207 ','Design and Analysis of Algorithms                          ');
INSERT INTO courses VALUES('CS223 ','Computer Architecture and Organization                     ');
INSERT INTO courses VALUES('CS245 ','Database Management Systems                                ');
INSERT INTO courses VALUES('CS344 ','Databases                                                  ');
INSERT INTO courses VALUES('CS346 ','Compilers                                                  ');
INSERT INTO courses VALUES('CS348 ','Computer Networks                                          ');
INSERT INTO courses VALUES('CS350M','Computer Systems                                           ');
INSERT INTO courses VALUES('CS503 ','Randomized Algorithms                                      ');
INSERT INTO courses VALUES('CS508 ','Optimization Methods                                       ');
INSERT INTO courses VALUES('CS528 ','High Performance Computing                                 ');
INSERT INTO courses VALUES('CS544 ','Topics in Networks                                         ');
INSERT INTO courses VALUES('CS549 ','Computer & Network Security                                ');
INSERT INTO courses VALUES('CS577 ','C-Based VLSI Design: Synthesis Optimization and Verificati ');
INSERT INTO courses VALUES('CS579 ','Automata Logic and Games                                   ');
INSERT INTO courses VALUES('DD111 ','Form Order & Structure                                     ');
INSERT INTO courses VALUES('DD112 ','Principlies of Visual Design                               ');
INSERT INTO courses VALUES('DD212 ','Visual Narratives                                          ');
INSERT INTO courses VALUES('DD213 ','Art and Aesthetics in Design                               ');
INSERT INTO courses VALUES('DD214 ','Design Workshop                                            ');
INSERT INTO courses VALUES('DD215 ','Cognitive Ergonomics                                       ');
INSERT INTO courses VALUES('DD220M','Introduction - Ergonomics                                  ');
INSERT INTO courses VALUES('DD311 ','Systems Approach - Design                                  ');
INSERT INTO courses VALUES('DD312 ','Design Evaluation Methods                                  ');
INSERT INTO courses VALUES('DD320M','Product Planning and Strategy                              ');
INSERT INTO courses VALUES('DD324 ','Plastics & Composites                                      ');
INSERT INTO courses VALUES('DD411 ','Design and Entrepreneurship                                ');
INSERT INTO courses VALUES('DD499 ','Design Project IV                                          ');
INSERT INTO courses VALUES('DD509 ','Interaction Design                                         ');
INSERT INTO courses VALUES('DD516 ','Digital Human Modelling and Simulation in Product Design   ');
INSERT INTO courses VALUES('DD525 ','Structural Packaging Design                                ');
INSERT INTO courses VALUES('DD532 ','Motion Graphics                                            ');
INSERT INTO courses VALUES('DD602 ','System Analysis & Information Design                       ');
INSERT INTO courses VALUES('DD702 ','Indian Traditional Form in Contemprary Design  Seminar     ');
INSERT INTO courses VALUES('DD705 ','Design Research Methods                                    ');
INSERT INTO courses VALUES('DD710 ','Research-based Project                                     ');
INSERT INTO courses VALUES('EE206 ','Analog Circuits                                            ');
INSERT INTO courses VALUES('EE213M','Digital Circuits                                           ');
INSERT INTO courses VALUES('EE230 ','Probability and Random Processes                           ');
INSERT INTO courses VALUES('EE250 ','Control Systems                                            ');
INSERT INTO courses VALUES('EE252 ','Measurement and Instrumentation                            ');
INSERT INTO courses VALUES('EE322M','Signal Processing                                          ');
INSERT INTO courses VALUES('EE333 ','Communication Networks                                     ');
INSERT INTO courses VALUES('EE337 ','Information Theory and Coding                              ');
INSERT INTO courses VALUES('EE340 ','Electromagnetic Theory                                     ');
INSERT INTO courses VALUES('EE351 ','Advanced Control Systems                                   ');
INSERT INTO courses VALUES('EE360 ','Embedded Systems                                           ');
INSERT INTO courses VALUES('EE385 ','Power Electronics and Drives                               ');
INSERT INTO courses VALUES('EE512 ','Analog IC Design                                           ');
INSERT INTO courses VALUES('EE515 ','VLSI System Design                                         ');
INSERT INTO courses VALUES('EE516 ','VLSI DSP                                                   ');
INSERT INTO courses VALUES('EE522 ','Statistical Signal Processing                              ');
INSERT INTO courses VALUES('EE525 ','Advanced Topics in Machine Learning                        ');
INSERT INTO courses VALUES('EE526 ','Machine Learning                                           ');
INSERT INTO courses VALUES('EE533 ','Wireless Communication                                     ');
INSERT INTO courses VALUES('EE535 ','Data Communication Network                                 ');
INSERT INTO courses VALUES('EE543 ','Computational Electromagnetics                             ');
INSERT INTO courses VALUES('EE544 ','Photonics Devices and Circuits                             ');
INSERT INTO courses VALUES('EE547 ','Optical Networks                                           ');
INSERT INTO courses VALUES('EE553 ','Optimal Control                                            ');
INSERT INTO courses VALUES('EE554 ','Nonlinear Systems and Control                              ');
INSERT INTO courses VALUES('EE562 ','Power Electronics Applications in Power Systems            ');
INSERT INTO courses VALUES('EE580 ','Electrical Machines and Drive Systems                      ');
INSERT INTO courses VALUES('EE592 ','Detection and Estimation Theory                            ');
INSERT INTO courses VALUES('EE595H','Stochastic Models                                          ');
INSERT INTO courses VALUES('EE596H','Optimization Techniques                                    ');
INSERT INTO courses VALUES('EE611 ','Organic Semiconductor Devices                              ');
INSERT INTO courses VALUES('EE613 ','Radio Frequency Integrated Circuits                        ');
INSERT INTO courses VALUES('EE621 ','Computer Vision                                            ');
INSERT INTO courses VALUES('EE622 ','Biomedical Signal Processing                               ');
INSERT INTO courses VALUES('EE624 ','Speech Technology                                          ');
INSERT INTO courses VALUES('EE630 ','Mobile communication                                       ');
INSERT INTO courses VALUES('EE638 ','Massive MIMO for 5G Communications: Design and Analysis    ');
INSERT INTO courses VALUES('EE643 ','Silicon Photonics                                          ');
INSERT INTO courses VALUES('EE655 ','Mathematical Techniques for Control and Signal Processing  ');
INSERT INTO courses VALUES('EE672 ','Electrical Power Quality and Reliability                   ');
INSERT INTO courses VALUES('EE674 ','Sychrophasor Technology                                    ');
INSERT INTO courses VALUES('EE694 ','Introduction - Parallel Computing                          ');
INSERT INTO courses VALUES('EE721 ','Advanced Topics in Signal Processing                       ');
INSERT INTO courses VALUES('EN671 ','Solar Energy Conversion Technology                         ');
INSERT INTO courses VALUES('EN674 ','Energy Efficiency Planning and Management                  ');
INSERT INTO courses VALUES('EN675 ','Photovoltaic Devices and Systems                           ');
INSERT INTO courses VALUES('HS113 ','Cognitive Psychology                                       ');
INSERT INTO courses VALUES('HS114 ','Cultural Theory and Practice                               ');
INSERT INTO courses VALUES('HS115 ','Leadership and Communication in Historical Drama           ');
INSERT INTO courses VALUES('HS116 ','Sociology of India: Conformities and Contradictions        ');
INSERT INTO courses VALUES('HS123 ','Game Theory and Economics                                  ');
INSERT INTO courses VALUES('HS125 ','Macroeconomics                                             ');
INSERT INTO courses VALUES('HS134 ','Introduction - Archaeology                                 ');
INSERT INTO courses VALUES('HS136 ','Introduction - Indian constitution and political processes ');
INSERT INTO courses VALUES('HS138 ','Psychology of Well Being                                   ');
INSERT INTO courses VALUES('HS203 ','Problems of Philosophy                                     ');
INSERT INTO courses VALUES('HS232 ','Linguistic Analysis                                        ');
INSERT INTO courses VALUES('HS238 ','Topics in Bilingualism                                     ');
INSERT INTO courses VALUES('HS401 ','Management of Organizational Behaviour                     ');
INSERT INTO courses VALUES('HS406 ','Philosophical Issues                                       ');
INSERT INTO courses VALUES('HS409 ','Environmental Economics                                    ');
INSERT INTO courses VALUES('HS415 ','History of Contemporary India                              ');
INSERT INTO courses VALUES('HS420 ','Writing Systems of the World                               ');
INSERT INTO courses VALUES('HS421 ','Sociological Perspectives on Modernity                     ');
INSERT INTO courses VALUES('HS422 ','Subaltern Voices and Narratives                            ');
INSERT INTO courses VALUES('HS423 ','Masculinities in Literature and Popular Culture            ');
INSERT INTO courses VALUES('HS424 ','Economics of Uncertainty and Information                   ');
INSERT INTO courses VALUES('HS425 ','Literature and Science Writing                             ');
INSERT INTO courses VALUES('HS427 ','Transboundary Waters: Conflict and Cooperation             ');
INSERT INTO courses VALUES('HS429 ','Indian Business History                                    ');
INSERT INTO courses VALUES('HS503 ','Sociology of Development                                   ');
INSERT INTO courses VALUES('HS517 ','Comparative Politics in Developing Countries               ');
INSERT INTO courses VALUES('HS523 ','Economic Development: Theory and Practice                  ');
INSERT INTO courses VALUES('HS524 ','Qualitative Research Methods in Social Sciences            ');
INSERT INTO courses VALUES('HS525 ','Indias Development: Issues and Debates                     ');
INSERT INTO courses VALUES('HS604 ','Development Finance                                        ');
INSERT INTO courses VALUES('HS621 ','Public Health and Development in India                     ');
INSERT INTO courses VALUES('HS623 ','Public Programmes and Social Accountability                ');
INSERT INTO courses VALUES('HS625 ','Environment History of India                               ');
INSERT INTO courses VALUES('HS702 ','Contemporary studies in Philosophy                         ');
INSERT INTO courses VALUES('HS707 ','Invisible Exchanges                                        ');
INSERT INTO courses VALUES('HS714 ','Understanding Organizational Behaviour: Theory and Resear  ');
INSERT INTO courses VALUES('HS715 ','Seminar course &Psychology                                 ');
INSERT INTO courses VALUES('HS719 ','Philosophy of Religion                                     ');
INSERT INTO courses VALUES('HS721 ','Research in Cultural Studies                               ');
INSERT INTO courses VALUES('HS722 ','Cultural Anthropology                                      ');
INSERT INTO courses VALUES('HS726 ','History of Assam                                           ');
INSERT INTO courses VALUES('HS727 ','Issues in Historical Research                              ');
INSERT INTO courses VALUES('HS730 ','Research Methods in Sociology                              ');
INSERT INTO courses VALUES('HS733 ','Issues in Phonological Theory                              ');
INSERT INTO courses VALUES('HS745 ','Phonological Acquisition                                   ');
INSERT INTO courses VALUES('HS753 ','Topics in International Relations                          ');
INSERT INTO courses VALUES('HS767 ','The Material Text & its Other                              ');
INSERT INTO courses VALUES('HS780 ','Understanding Social Movements                             ');
INSERT INTO courses VALUES('HS781 ','Approaches - Diplomatic and Military History               ');
INSERT INTO courses VALUES('MA102 ','Mathematics II                                             ');
INSERT INTO courses VALUES('MA212M','Mathematical Statistics                                    ');
INSERT INTO courses VALUES('MA224 ','Real Analysis                                              ');
INSERT INTO courses VALUES('MA252 ','Design and Analysis of Algorithms                          ');
INSERT INTO courses VALUES('MA271 ','Financial Engineering I                                    ');
INSERT INTO courses VALUES('MA312M','Modern Algebra                                             ');
INSERT INTO courses VALUES('MA321 ','Optimization                                               ');
INSERT INTO courses VALUES('MA351 ','Formal Languages and Automata Theory                       ');
INSERT INTO courses VALUES('MA373 ','Financial Engineering II                                   ');
INSERT INTO courses VALUES('MA473 ','Computational Finance                                      ');
INSERT INTO courses VALUES('MA477 ','Financial Risk Management And Modeling                     ');
INSERT INTO courses VALUES('MA510 ','Combinatorics                                              ');
INSERT INTO courses VALUES('MA512 ','Data Structures and Algorithms                             ');
INSERT INTO courses VALUES('MA513 ','Parallel Computing                                         ');
INSERT INTO courses VALUES('MA542 ','Differential Equation                                      ');
INSERT INTO courses VALUES('MA547 ','Complex Analysis                                           ');
INSERT INTO courses VALUES('MA561 ','Fluid Dynamics                                             ');
INSERT INTO courses VALUES('MA562 ','Mathematical Modelling and Numerical Simulation            ');
INSERT INTO courses VALUES('MA571 ','Numerical Linear Algebra                                   ');
INSERT INTO courses VALUES('MA573 ','Numerics of Partial Differential Equations                 ');
INSERT INTO courses VALUES('MA590 ','Probability Theory and Random Processes                    ');
INSERT INTO courses VALUES('MA591 ','Optimization Techniques                                    ');
INSERT INTO courses VALUES('MA597 ','Queueing Theory and Applications                           ');
INSERT INTO courses VALUES('MA601 ','Graphs and Matrices                                        ');
INSERT INTO courses VALUES('MA621 ','Rings and Modules                                          ');
INSERT INTO courses VALUES('MA622 ','Galois Theory                                              ');
INSERT INTO courses VALUES('MA625 ','Linear Algebra -1                                          ');
INSERT INTO courses VALUES('MA641 ','Operator Theory in Hilbert Spaces                          ');
INSERT INTO courses VALUES('MA642 ','Real Analysis -1                                           ');
INSERT INTO courses VALUES('MA643 ','Algebraic Topology                                         ');
INSERT INTO courses VALUES('MA651 ','Distributed Algorithms                                     ');
INSERT INTO courses VALUES('MA662 ','Differential Equations                                     ');
INSERT INTO courses VALUES('MA663 ','Fractional Calculus and Fractional Differential Equations  ');
INSERT INTO courses VALUES('MA671 ','Finite Element Methods for Partial Differential Equations  ');
INSERT INTO courses VALUES('MA683 ','Probability Theory                                         ');
INSERT INTO courses VALUES('MA685 ','Martingales and Brownian Motion                            ');
INSERT INTO courses VALUES('MA686 ','Random Graphs                                              ');
INSERT INTO courses VALUES('MA687 ','Generalized Linear Models                                  ');
INSERT INTO courses VALUES('ME101 ','Engineering Mechanics                                      ');
INSERT INTO courses VALUES('ME221 ','Fluid Mechanics II                                         ');
INSERT INTO courses VALUES('ME222 ','Manufacturing Technology I                                 ');
INSERT INTO courses VALUES('ME223 ','Solid Mechanics II                                         ');
INSERT INTO courses VALUES('ME224 ','Kinematics of Machinery                                    ');
INSERT INTO courses VALUES('ME321 ','Applied Thermodynamics                                     ');
INSERT INTO courses VALUES('ME322 ','Machine Design                                             ');
INSERT INTO courses VALUES('ME323 ','Mechanical Measurements                                    ');
INSERT INTO courses VALUES('ME324 ','Heat and Mass Transfer                                     ');
INSERT INTO courses VALUES('ME325 ','Control Systems                                            ');
INSERT INTO courses VALUES('ME421 ','Industrial Engineering and Operation Research              ');
INSERT INTO courses VALUES('ME511 ','Advanced Materials and Processing                          ');
INSERT INTO courses VALUES('ME513 ','Physics of Manufacturing Process                           ');
INSERT INTO courses VALUES('ME522 ','Convective Heat & Mass Transfer                            ');
INSERT INTO courses VALUES('ME541 ','Continuum Mechanics                                        ');
INSERT INTO courses VALUES('ME542 ','Numerical Analysis                                         ');
INSERT INTO courses VALUES('ME552 ','Aircraft Propulsion                                        ');
INSERT INTO courses VALUES('ME553 ','Gas Dynamics                                               ');
INSERT INTO courses VALUES('ME554 ','Rocket Propulsion                                          ');
INSERT INTO courses VALUES('ME605 ','Fracture Fatigue and Failure Analysis                      ');
INSERT INTO courses VALUES('ME607 ','Introduction - Composite Materials                         ');
INSERT INTO courses VALUES('ME608 ','Computer Aided Design-Computer Aided Manufacturing         ');
INSERT INTO courses VALUES('ME615 ','Rotor Dynamics                                             ');
INSERT INTO courses VALUES('ME617 ','Hydrodynamic Stability and Transition - Turbulence         ');
INSERT INTO courses VALUES('ME619 ','Fundamentals of Microfluidics                              ');
INSERT INTO courses VALUES('ME648 ','Viscous Fluid Flow                                         ');
INSERT INTO courses VALUES('ME657 ','Two Phase Flow & Heat Transfer                             ');
INSERT INTO courses VALUES('ME674 ','Soft Computing in Engineering                              ');
INSERT INTO courses VALUES('ME675 ','Advanced Welding Processes                                 ');
INSERT INTO courses VALUES('ME682 ','Nonlinear Finite Element Methods                           ');
INSERT INTO courses VALUES('ME688 ','Advanced Machining Processes                               ');
INSERT INTO courses VALUES('ME696 ','Biomedical Devices and Systems                             ');
INSERT INTO courses VALUES('PH102 ','Physics II                                                 ');
INSERT INTO courses VALUES('PH202 ','Electromagnetics                                           ');
INSERT INTO courses VALUES('PH204 ','Quantum Mechanics I                                        ');
INSERT INTO courses VALUES('PH206 ','Computational Physics                                      ');
INSERT INTO courses VALUES('PH208 ','Digital electronics and microprocessors                    ');
INSERT INTO courses VALUES('PH282M','Engineering Optics                                         ');
INSERT INTO courses VALUES('PH302 ','Solid State Physics                                        ');
INSERT INTO courses VALUES('PH304 ','Engineering Optics                                         ');
INSERT INTO courses VALUES('PH306 ','Nuclear Science and Engineering                            ');
INSERT INTO courses VALUES('PH308 ','Measurement Techniques                                     ');
INSERT INTO courses VALUES('PH402 ','Mathematical Physics II                                    ');
INSERT INTO courses VALUES('PH404 ','Statistical Mechanics                                      ');
INSERT INTO courses VALUES('PH406 ','Quantum Mechanics II                                       ');
INSERT INTO courses VALUES('PH408 ','Numerical Methods & Computational Physics                  ');
INSERT INTO courses VALUES('PH410 ','Electrodynamics I                                          ');
INSERT INTO courses VALUES('PH414 ','Nanoelectronics and Nanophotonics                          ');
INSERT INTO courses VALUES('PH446 ','Fundamentals of Astrophysics                               ');
INSERT INTO courses VALUES('PH458 ','Applied superconductivity                                  ');
INSERT INTO courses VALUES('PH465 ','Optoelectronics                                            ');
INSERT INTO courses VALUES('PH521 ','Topics in condensed matter Physics                         ');
INSERT INTO courses VALUES('PH522 ','Physics of Semiconductors                                  ');
INSERT INTO courses VALUES('PH525 ','Optoelectronic devices                                     ');
INSERT INTO courses VALUES('PH534 ','Fibre Optics                                               ');
INSERT INTO courses VALUES('PH541 ','Quantum Computation and Quantum Information                ');
INSERT INTO courses VALUES('PH543 ','Quantum Field Theory                                       ');
INSERT INTO courses VALUES('PH544 ','High Energy Physics                                        ');
INSERT INTO courses VALUES('PH702 ','Statistical methods in condensed matter physics            ');
INSERT INTO courses VALUES('PH704 ','Guided and Fourier wave optics                             ');
INSERT INTO courses VALUES('PH706 ','Gravitation and cosmology                                  ');
INSERT INTO courses VALUES('RT514 ','Water Resources Management                                 ');
INSERT INTO courses VALUES('RT515 ','Natural Resources Management                               ');
INSERT INTO courses VALUES('RT517 ','Agri-horticultural Produce Processing Technology           ');
INSERT INTO courses VALUES('RT520 ','Field Work and Effective Communication                     ');
