
CREATE TABLE rooms(room_id char(20),room_location char(40),CONSTRAINT rid01 PRIMARY KEY(room_id));

INSERT INTO rooms VALUES('1004','Core I');
INSERT INTO rooms VALUES('1201','Core I');
INSERT INTO rooms VALUES('1202','Core I');
INSERT INTO rooms VALUES('1205','Core I');
INSERT INTO rooms VALUES('1G1','Gallery I');
INSERT INTO rooms VALUES('1G2','Gallery I');
INSERT INTO rooms VALUES('2001','Core II');
INSERT INTO rooms VALUES('2002','Core II');
INSERT INTO rooms VALUES('2101','Core II');
INSERT INTO rooms VALUES('2102','Core II');
INSERT INTO rooms VALUES('2201','Core II');
INSERT INTO rooms VALUES('2202','Core II');
INSERT INTO rooms VALUES('2203','Core II');
INSERT INTO rooms VALUES('2204','Core II');
INSERT INTO rooms VALUES('3003','Core III');
INSERT INTO rooms VALUES('3101','Core III');
INSERT INTO rooms VALUES('3102','Core III');
INSERT INTO rooms VALUES('3202','Core III');
INSERT INTO rooms VALUES('4201','Core IV');
INSERT INTO rooms VALUES('4202','Core IV');
INSERT INTO rooms VALUES('4G1','Gallery IV');
INSERT INTO rooms VALUES('4G2','Gallery IV');
INSERT INTO rooms VALUES('5001','Core V');
INSERT INTO rooms VALUES('5002','Core V');
INSERT INTO rooms VALUES('5003','Core V');
INSERT INTO rooms VALUES('5004','Core V');
INSERT INTO rooms VALUES('CC-LAB','CC');
INSERT INTO rooms VALUES('DH1','DH');
INSERT INTO rooms VALUES('DH2','DH');
INSERT INTO rooms VALUES('L1','Lecture Hall');
INSERT INTO rooms VALUES('L2','Lecture Hall');
INSERT INTO rooms VALUES('L3','Lecture Hall');
INSERT INTO rooms VALUES('L4','Lecture Hall');
